const e=JSON.parse('{"key":"v-7bfa8031","path":"/interview/exception.html","title":"Java 异常面试总结","lang":"zh-CN","frontmatter":{"title":"Java 异常面试总结","icon":"java","isOriginal":true,"date":"2022-08-07T00:01:00.000Z","tag":["面试","异常","Java"],"category":["面试宝典"],"summary":"异常简介 异常类层次结构 从结构图可以看出，所有异常均继承自 Throwable 类，它有两个重要的子类：Exception 和 Error ，各自又包含大量子类。 1. Exception 程序本身可以处理的异常，又可以分为 受检异常 和 非受检异常 ，受检异常 可以用 try...catch... 语句进行捕获处理，而且能从异常中恢复。但 非受检异常 是","head":[["meta",{"property":"og:url","content":"https://cunyu1943.github.io/JavaPark/interview/exception.html"}],["meta",{"property":"og:site_name","content":"JavaPark"}],["meta",{"property":"og:title","content":"Java 异常面试总结"}],["meta",{"property":"og:type","content":"article"}],["meta",{"property":"og:locale","content":"zh-CN"}],["meta",{"property":"article:tag","content":"面试"}],["meta",{"property":"article:tag","content":"异常"}],["meta",{"property":"article:tag","content":"Java"}],["meta",{"property":"article:published_time","content":"2022-08-07T00:01:00.000Z"}]]},"excerpt":"","headers":[{"level":2,"title":"异常简介","slug":"异常简介","link":"#异常简介","children":[{"level":3,"title":"异常类层次结构","slug":"异常类层次结构","link":"#异常类层次结构","children":[]},{"level":3,"title":"Throwable 常用方法","slug":"throwable-常用方法","link":"#throwable-常用方法","children":[]},{"level":3,"title":"try-catch-finally 和 try-with-resources","slug":"try-catch-finally-和-try-with-resources","link":"#try-catch-finally-和-try-with-resources","children":[]}]},{"level":2,"title":"异常处理","slug":"异常处理","link":"#异常处理","children":[{"level":3,"title":"声明异常","slug":"声明异常","link":"#声明异常","children":[]},{"level":3,"title":"抛出异常","slug":"抛出异常","link":"#抛出异常","children":[]},{"level":3,"title":"捕获异常","slug":"捕获异常","link":"#捕获异常","children":[]}]},{"level":2,"title":"异常常见面试题","slug":"异常常见面试题","link":"#异常常见面试题","children":[{"level":3,"title":"Error 和 Exception 的区别？","slug":"error-和-exception-的区别","link":"#error-和-exception-的区别","children":[]},{"level":3,"title":"运行时异常和受检异常的区别？","slug":"运行时异常和受检异常的区别","link":"#运行时异常和受检异常的区别","children":[]},{"level":3,"title":"throw 和 throws 的区别？","slug":"throw-和-throws-的区别","link":"#throw-和-throws-的区别","children":[]},{"level":3,"title":"final、finally、finallize 的区别？","slug":"final、finally、finallize-的区别","link":"#final、finally、finallize-的区别","children":[]},{"level":3,"title":"常见的 RuntimeException 异常？","slug":"常见的-runtimeexception-异常","link":"#常见的-runtimeexception-异常","children":[]},{"level":3,"title":"JVM 如何处理异常？","slug":"jvm-如何处理异常","link":"#jvm-如何处理异常","children":[]}]}],"git":{},"readingTime":{"minutes":7.12,"words":2136},"copyright":"著作权归村雨遥所有\\n基于转载请注明以下信息：『作者：村雨遥，博客：https://cunyu1943.github.io/JavaPark』协议\\n原文链接：https://cunyu1943.github.io/JavaPark/interview/exception.html","filePathRelative":"interview/exception.md","localizedDate":"2022年8月7日"}');export{e as data};
